### PR TITLE
Fix app version and add new var on auth completion

### PR DESCRIPTION
**Pull request by seia-soto**
This PR fixes the version of application and adds new variant of auth completion response.

Also, I am one of who tries to dig APIs of clubhouse just like you.

If you need, you can grab latest app version things from [here](https://github.com/Seia-Soto/clubhouse-api/blob/master/src/profiles/application/a297.js) and locale things [here](https://github.com/Seia-Soto/clubhouse-api/blob/master/src/profiles/locales).

### CODE REVIEW

**Comment by seia-soto** [comment]
Also, I don't know what `scale` means in user-agent, but I think this maybe make reverse-engineers struggle, and trying to know by collecting many samples as I can.

**Comment by zhuowei** [comment]
Whoops: good catch! Thanks.

**Comment by zhuowei** [comment]
`scale` is just the Retina scale factor of the device - it's the default user-agent from [AFNetworking](https://stackoverflow.com/questions/29477229/setting-user-agent-in-afnetworking).

I think Clubhouse's API only checks the user-agent for "clubhouse" currently though.

**Comment by seia-soto** [comment]
Oh, really thanks for information!

**Pull request merged**
